-- Este codigo fue generado con las herramientas de exportacion de workbench
-- Pero este codigo no se va utilizar en mySQL, el manejador de base de datos
-- que se utilizara en el proyecto es MariaDB ya que es el que viene por defecto
-- en XAMPP, hay notaciones que se dejan de lado y se cambian con respecto al codigo
-- generado, para poder ser utilizadas en MariaDB

-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 13:42:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema INVENTARIO_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema INVENTARIO_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INVENTARIO_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `INVENTARIO_DB` ;

-- -----------------------------------------------------
-- Table `INVENTARIO_DB`.`AREAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTARIO_DB`.`AREAS` (
  `id_area` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVENTARIO_DB`.`LOCALIZACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTARIO_DB`.`LOCALIZACIONES` (
  `id_localizacion` INT PRIMARY KEY NOT NULL auto_increment,
  `area_id` INT NOT NULL,
  `digito_2` INT NOT NULL,
  `digito_3` INT NOT NULL,
  `descripcion` VARCHAR(60) NULL,
  CONSTRAINT `area_localizacion`
    FOREIGN KEY (`area_id`)
    REFERENCES `INVENTARIO_DB`.`AREAS` (`id_area`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVENTARIO_DB`.`TIPO_DE_MATERIALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTARIO_DB`.`TIPO_DE_MATERIALES` (
  `id_tipo_de_material` INT NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_tipo_de_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVENTARIO_DB`.`MATERIALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTARIO_DB`.`MATERIALES` (
  `id_material` INT PRIMARY KEY NOT NULL auto_increment,
  `tipo_de_material_id` INT NOT NULL,
  `digito_5` INT NOT NULL,
  `digito_6` INT NOT NULL,
  `nombre_del_material` VARCHAR(90) NULL,
  `descripcion` TEXT NULL,
  CONSTRAINT `tipo_de_material_material`
    FOREIGN KEY (`tipo_de_material_id`)
    REFERENCES `INVENTARIO_DB`.`TIPO_DE_MATERIALES` (`id_tipo_de_material`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVENTARIO_DB`.`INVENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTARIO_DB`.`INVENTARIO` (
  `id_inventario` VARCHAR(13) PRIMARY KEY NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  `localizacion_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `digito_7` INT NOT NULL,
  `digito_8` INT NOT NULL,
  `etiquetado` BOOLEAN NULL,
  CONSTRAINT `localizacion_inventario`
    FOREIGN KEY (`localizacion_id`)
    REFERENCES `INVENTARIO_DB`.`LOCALIZACIONES` (`id_localizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `material_inventario`
    FOREIGN KEY (`material_id`)
    REFERENCES `INVENTARIO_DB`.`MATERIALES` (`id_material`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
